<Project>
  <PropertyGroup Label="Package Info">
    <RepositoryUrl>https://github.com/NotroDev/SkFluentAvalonia</RepositoryUrl>
    <PackageProjectUrl>https://github.com/NotroDev/SkFluentAvalonia</PackageProjectUrl>
    <Description>Fork of FluentAvalonia maintained for SkEditor. Brings fluent design and WinUI controls into Avalonia with custom tweaks.</Description>
    <PackageTags>c-sharp;xaml;cross-platform;dotnet;avalonia;avaloniaui;fluent;skeditor</PackageTags>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <Version>3.0.2</Version>
    <AssemblyVersion>3.0.2.0</AssemblyVersion>
    <PackageReadmeFile>README.md</PackageReadmeFile>
  </PropertyGroup>

  <!-- Add Package Icon -->
  <PropertyGroup>
    <PackageIcon>SkFA.png</PackageIcon>
  </PropertyGroup>

  <ItemGroup Label="Package Assets">
    <None Include="$(MSBuildThisFileDirectory)/../Assets/SkFA.png" Pack="true" Visible="false" PackagePath=""/>
    <None Include="$(MSBuildThisFileDirectory)/../README.md" Pack="true" Visible="false" PackagePath=""/>
  </ItemGroup>

  <Import Project="$(MSBuildThisFileDirectory)/SourceLink.props"/>
</Project>
